name: "Trivy Scan"
#Define that this workflow can be reused
on:
#Determine the secrets which need to be populated during runtime
  workflow_call:
    secrets:
      gh_token:
        required: true
      aqua_key:
        required: true
      aqua_secret:
        required: true
#Which permissions are needed
permissions: write-all
#The following is provided from the Supply Chain Module
jobs:
  build:
    name: Build
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Trivy 
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          security-checks: 'vuln,config,secret'
          hide-progress: false
          format: 'table'
        env:
          AQUA_KEY: "${{ secrets.AQUA_KEY }}"
          AQUA_SECRET: "${{ secrets.AQUA_SECRET }}"
          TRIVY_RUN_AS_PLUGIN: "aqua"
          GITHUB_TOKEN: "${{ github.token }}"
