name: Aqua Scanner
on:
  workflow_call:
    inputs:
      ARTIFACT_PATH:
        description: "Path to artifact"
        required: true
        type: string
      GH_TOKEN: 
      description: "github token used in source pipeline"
      required: true
      type: string
    secrets:
      AQUA_KEY:
        description: "Aqua Key"
        required: true
      AQUA_SECRET:
        description: "Aqua Secret"
        required: true
      DOCKERHUB_USERNAME:
        description: "dockerhub username"
        required: true
      DOCKERHUB_TOKEN:
        description: "dockerhub access token"
        required: true
jobs:
  aqua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run Aqua scanner
        uses: docker://aquasec/aqua-scanner
        with:
          args: trivy fs --debug --scanners config,vuln,secret . --package-json --sast --reachability
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          GITHUB_TOKEN: ${{ github.token }}
          TRIVY_RUN_AS_PLUGIN: "aqua"
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Manifest Generation
        run: |
          export BILLY_SERVER=https://billy.codesec.aquasec.com
          curl -sLo install.sh download.codesec.aquasec.com/billy/install.sh
          curl -sLo install.sh.checksum https://github.com/argonsecurity/releases/releases/latest/download/install.sh.checksum
          if ! cat install.sh.checksum | sha256sum ; then
          echo "install.sh checksum failed"
          exit 1
          fi
          BINDIR="." sh install.sh
          rm install.sh install.sh.checksum
          ./billy generate \
            --access-token "${{ inputs.GH_TOKEN }}" \
            --aqua-key "${{ secrets.AQUA_KEY }}" \
            --aqua-secret "${{ secrets.AQUA_SECRET }}" \
            --artifact-path "${{inputs.ARTIFACT_PATH}}:${{ github.sha }}"
