name: Aqua Scanner
on:
  workflow_call:
    inputs:
      AQUA_URL:
        description: "Aqua URL"
        type: string
      CSPM_URL:
        description: "CSPM URL"
        type: string
    secrets:
      AQUA_KEY:
        description: "Aqua Key"
        required: true
      AQUA_SECRET:
        description: "Aqua Secret"
        required: true
      GH_TOKEN:
        description: "GitHub token"
        required: true

jobs:
  aqua:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Aqua scanner
        uses: docker://aquasec/aqua-scanner
        with:
          args: trivy fs --package-json --sast --debug --security-checks config,vuln,secret .
        env:
          AQUA_KEY: ${{ secrets.AQUA_KEY }}
          AQUA_SECRET: ${{ secrets.AQUA_SECRET }}
          GITHUB_TOKEN: ${{ github.token }}
          AQUA_URL: ${{ inputs.AQUA_URL }}
          CSPM_URL: ${{ inputs.CSPM_URL }}
          TRIVY_RUN_AS_PLUGIN: "aqua"
